# All SpaceVim option below [option] section
[options]
  # set spacevim theme. by default colorscheme layer is not loaded,
  # if you want to use more colorscheme, please load the colorscheme
  # layer

  #colorscheme = "desert"
  #colorscheme = "palenight"
  #colorscheme = "molokai"
  #colorscheme = "NeoSolarized"
  colorscheme = "gruvbox"
  colorscheme_bg = "dark"
  #colorscheme_bg = "light"
  #colorscheme_bg = "term"
  #colorscheme_bg = "statusline"
  #colorscheme_bg = "gui"
 
  # options for statusline
  # Set the statusline separators of statusline, default is "arrow"
  statusline_separator = "arrow"
  # Set the statusline separators of inactive statusline
  statusline_inactive_separator = "bar"

  # Set SpaceVim buffer index type
  buffer_index_type = 4
  # 0: 1 ➛ ➊
  # 1: 1 ➛ ➀
  # 2: 1 ➛ ⓵
  # 3: 1 ➛ ¹
  # 4: 1 ➛ 1

  # Enable/Disable show mode on statusline
  enable_statusline_mode = true

  # Enable automatic update
  automatic_update = true
  # left sections of statusline
  statusline_left_sections = [
     'winnr',
     'major mode',
     'filename',
     'fileformat',
     'minor mode lighters',
     'version control info',
     'search status'
  ]
  # right sections of statusline
  statusline_right_sections = [
     'cursorpos',
     'percentage',
     'input method',
     'date',
     'time'
  ]

  filetree_direction = "left"

  filemanager = "nerdtree"
  enable_vimfiler_gitstatus = true

  # keep q for recording a macro
  windows_smartclose = ''

  # Disable guicolors in basic mode, many terminal do not support 24bit
  # true colors
  enable_guicolors = true
  # Disable statusline separator, if you want to use other value, please
  # install nerd fonts
  statusline_separator = "arrow"
  statusline_inactive_separator = "arrow"
  buffer_index_type = 4
  enable_tabline_filetype_icon = true
  enable_statusline_mode = false
  bootstrap_before = 'myspacevim#before'
  bootstrap_after = 'myspacevim#after'
  autocomplete_method = "ycm"
  snippet_engine = "ultisnips"

  #guifont = "SourceCodePro Nerd Font Mono:h11"

  #'winnr' window number
  #'syntax checking'
  #'filename' file name
  #'fileformat' file format
  #'major mode'
  #'minor mode lighters'
  #'cursorpos' cursor position
  #'percentage' content range
  #'date' date
  #'time' time
  #'whitespace' line number with trailing space at the end
  #'battery status' battery status
  #'input method' input method
  #'search status' search index

[[layers]]
  name = "colorscheme"

[[layers]]
  name = 'VersionControl'

# Enable gtag layer
[[layers]]
  name = 'gtags'

# Enable autocomplete layer
[[layers]]
  name = 'autocomplete'
  auto-completion-return-key-behavior = "complete"
  auto-completion-tab-key-behavior = "smart"

[[layers]]
  name = 'shell'
  default_position = 'bottom'
  default_height = 20

[[layers]]
  name = "lang#c"

[[layers]]
  name = "lang#rust"
  racer_cmd ="$HOME/.cargo/bin/racer"

[[layers]]
  name = "lang#javascript"
  auto_fix = true
  enable_flow_syntax = true

[[layers]]
  name = "lang#java"

[[layers]]
  name = "git"
  git-plugin = "fugitive"

[[layers]]
  name = "github"

[[layers]]
  name = "fzf"

[[layers]]
  name = "tools"

[[layers]]
  name = "lang#dockerfile"

[[layers]]
  name = "lang#html"

[[layers]]
  name = "lang#go"

[[layers]]
  name = "lang#python"
  python_file_head = [
      '#!/usr/bin/env python3',
      '# -*- coding: utf-8 -*-',
      '',
      ''
  ]

[[layers]]
  name = "lang#lua"

[[layers]]
  name = "lsp"

[[layers]]
  name = "lang#swift"

[[layers]]
  name = "lang#sh"

[[layers]]
  name = "lang#bash"

[[layers]]
  name = "core#statusline"

[[custom_plugins]]
  name = "MaxMEllon/vim-jsx-pretty"
  merged = false

[[custom_plugins]]
  repo = "https://github.com/pearofducks/ansible-vim.git"
  merged = false

[[layers]]
  name = "ui"
  enable = true
  enable_sidebar = true

[[layers]]
  name = "japanese"

