name: Tinu Tests

on: [push, pull_request]

jobs:
  lines:
    name: Less than 1000 lines
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install sloccount and bats
      run: sudo apt-get update && sudo apt-get install sloccount -y

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Install bats
      run: sudo apt-get update && sudo apt-get install bats -y
    - name: Run bats
      run: cd test; bats dotfile.bats
