name: Tinu Tests

on: [push, pull_request]

jobs:
  lines:
    name: Less than 1000 lines
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install sudo
      run: apt-get update && apt-get install sudo -y
    - name: Install sloccount and bats
      run: sudo apt-get install sloccount bats -y
    - name: Check <1000 lines
      run: sloccount .rakibrc; if [ $(sloccount .rakibrc | sed -n 's/.*Total Physical Source Lines of Code (SLOC)[ ]*= \([^ ]*\).*/\1/p' | tr -d ',') -gt 1000 ]; then exit 1; fi

  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
    - name: Run bats
      run: cd test; bats dotfile.bats
